### PR TITLE
Feature/message modal

### PR DESCRIPTION
**Pull request by manzcode**
I'll implement a socket after the notification push feature.

### CODE REVIEW

**Comment by marktlinn** [comment]
@manzcode The code looks good, and the large screens it looks nice and functions well? But on mobile or smaller screens I can't see the input box to type when I click to send a message.

**Comment by manzcode** [comment]
ok,I'll made it now.

**Comment by manzcode** [comment]
The mobile interface is ready.

**Review by marktlinn — APPROVED** [review]
Looks good to me, nice work Mario!

**Pull request merged**
